cp .env repolya/app/
cp .env repolya/autogen/
cp .env repolya/azure/
cp .env repolya/chat/
cp .env repolya/coder/
cp .env repolya/metagpt/
cp .env repolya/paper/
cp .env repolya/rag/
cp .env repolya/toolset/
cp .env repolya/writer/
