from repolya._const import AUTOGEN_CONFIG
from repolya._log import logger_autogen

from repolya.autogen.tool_function import (
    image_review_replicate,
    text_to_image_generation,
    _def_image_review_replicate,
    _def_text_to_image_generation,
)

from autogen import (
    AssistantAgent,
    UserProxyAgent,
    config_list_from_json,
)


config_list = config_list_from_json(env_or_file=str(AUTOGEN_CONFIG))


# Base Configuration
base_config = {
    "config_list": config_list,
    "request_timeout": 120,
    "temperature": 0,
    "model": "gpt-3.5-turbo",
    # "use_cache": False,
    "seed": 42,
}


##### DRAW
DRAW_user = UserProxyAgent(
    name="DRAW_user",
    code_execution_config=False,
    human_input_mode="ALWAYS",
)


ARTIST_PROMPT = "You are a text to image AI model expert, you will use 'text_to_image_generation' function to generate image with prompt provided, and also improve prompt based on feedback provided until it is 10/10."
DRAW_artist = AssistantAgent(
    name="DRAW_artist",
    llm_config={
        **base_config,
        "functions": [
            _def_image_review_replicate, _def_text_to_image_generation,
        ],
    },
    function_map={
        "image_review_replicate": image_review_replicate,
        "text_to_image_generation": text_to_image_generation
    },
    system_message=ARTIST_PROMPT,
)


CRITIC_PROMPT = "You are an AI image critique, you will use 'image_review_replicate' function to review the image generated by the 'DRAW_artist' against the original prompt, and provide feedback on how to improve the prompt."
DRAW_critic = AssistantAgent(
    name="DRAW_critic",
    llm_config={
        **base_config,
        "functions": [
            _def_image_review_replicate, _def_text_to_image_generation,
        ],
    },
    function_map={
        "image_review_replicate": image_review_replicate,
        "text_to_image_generation": text_to_image_generation
    },
    system_message=CRITIC_PROMPT,
)

